-- In the output SQL perform the following find and replace:
--"[dbo].[ChannelManager_" => "[ChannelManager].["
--"[dbo].[DeviceManager_" => "[DeviceManager].["
--"[dbo].[ModbusMaster_" => "[ModbusMaster].["
--"[dbo].[RocMaster_" => "[RocMaster].["