-- In the output SQL perform the following find and replace:
--"[dbo].[Watchdog_" => "[Watchdog].["
--"[dbo].[ChannelManager_" => "[ChannelManager].["
--"[dbo].[DeviceManager_" => "[DeviceManager].["
--"[dbo].[MODBUSMaster_" => "[MODBUSMaster].["
--"[dbo].[ROCMaster_" => "[ROCMaster].["