CREATE TABLE [RocMaster].[FloBoss.103.MeterProcessVariableAlarms] (
    [RocMeterId]                         BIGINT                  NOT NULL,
    [DateTimeStamp]                      DATETIMEOFFSET (7)      CONSTRAINT [DF_FloBoss.103.MeterProcessVariableAlarms_DateTimeStamp] DEFAULT (sysdatetime()) NOT NULL,
    [DifferentialPressure.LowLowAlarm]   [RocMaster].[Parameter] NOT NULL,
    [DifferentialPressure.LowAlarm]      [RocMaster].[Parameter] NOT NULL,
    [DifferentialPressure.HighAlarm]     [RocMaster].[Parameter] NOT NULL,
    [DifferentialPressure.HighHighAlarm] [RocMaster].[Parameter] NOT NULL,
    [DifferentialPressure.RateAlarm]     [RocMaster].[Parameter] NOT NULL,
    [DifferentialPressure.Deadband]      [RocMaster].[Parameter] NOT NULL,
    [StaticPressure.LowLowAlarm]         [RocMaster].[Parameter] NOT NULL,
    [StaticPressure.LowAlarm]            [RocMaster].[Parameter] NOT NULL,
    [StaticPressure.HighAlarm]           [RocMaster].[Parameter] NOT NULL,
    [StaticPressure.HighHighAlarm]       [RocMaster].[Parameter] NOT NULL,
    [StaticPressure.RateAlarm]           [RocMaster].[Parameter] NOT NULL,
    [StaticPressure.Deadband]            [RocMaster].[Parameter] NOT NULL,
    [Temperature.LowLowAlarm]            [RocMaster].[Parameter] NOT NULL,
    [Temperature.LowAlarm]               [RocMaster].[Parameter] NOT NULL,
    [Temperature.HighAlarm]              [RocMaster].[Parameter] NOT NULL,
    [Temperature.HighHighAlarm]          [RocMaster].[Parameter] NOT NULL,
    [Temperature.RateAlarm]              [RocMaster].[Parameter] NOT NULL,
    [Temperature.Deadband]               [RocMaster].[Parameter] NOT NULL,
    [RowVersion]                         ROWVERSION              NOT NULL,
    CONSTRAINT [PK_FloBoss.103.MeterProcessVariableAlarms_1] PRIMARY KEY CLUSTERED ([RocMeterId] ASC),
    CONSTRAINT [FK_FloBoss.103.MeterProcessVariableAlarms_RocMeters] FOREIGN KEY ([RocMeterId]) REFERENCES [RocMaster].[RocMeters] ([Id])
);

