CREATE TABLE [FlowSQL].[DifferentialPressureMeterProcessVariableValues] (
    [MeterId]                              BIGINT             NOT NULL,
    [DateTimeStamp]                        DATETIMEOFFSET (7) NOT NULL,
    [DifferentialPressure.AlarmingEnabled] BIT                NOT NULL,
    [DifferentialPressure.ScanningEnabled] BIT                NOT NULL,
    [DifferentialPressure.ScanPeriod]      INT                NOT NULL,
    [DifferentialPressure.Filter]          INT                NOT NULL,
    [DifferentialPressure.Units]           VARCHAR (30)       NOT NULL,
    [DifferentialPressure.Raw.Value]       FLOAT (53)         NOT NULL,
    [DifferentialPressure.EU.Value]        FLOAT (53)         NOT NULL,
    [DifferentialPressure.Raw.ZeroValue]   INT                NOT NULL,
    [DifferentialPressure.Raw.SpanValue]   INT                NOT NULL,
    [DifferentialPressure.EU.ZeroValue]    FLOAT (53)         NOT NULL,
    [DifferentialPressure.EU.SpanValue]    FLOAT (53)         NOT NULL,
    [StaticPressure.AlarmingEnabled]       BIT                NOT NULL,
    [StaticPressure.ScanningEnabled]       BIT                NOT NULL,
    [StaticPressure.ScanPeriod]            INT                NOT NULL,
    [StaticPressure.Filter]                INT                NOT NULL,
    [StaticPressure.Units]                 VARCHAR (30)       NOT NULL,
    [StaticPressure.Raw.Value]             FLOAT (53)         NOT NULL,
    [StaticPressure.EU.Value]              FLOAT (53)         NOT NULL,
    [StaticPressure.Raw.ZeroValue]         INT                NOT NULL,
    [StaticPressure.Raw.SpanValue]         INT                NOT NULL,
    [StaticPressure.EU.ZeroValue]          FLOAT (53)         NOT NULL,
    [StaticPressure.EU.SpanValue]          FLOAT (53)         NOT NULL,
    [Temperature.AlarmingEnabled]          BIT                NOT NULL,
    [Temperature.ScanningEnabled]          BIT                NOT NULL,
    [Temperature.ScanPeriod]               INT                NOT NULL,
    [Temperature.Filter]                   INT                NOT NULL,
    [Temperature.Units]                    VARCHAR (30)       NOT NULL,
    [Temperature.Raw.Value]                FLOAT (53)         NOT NULL,
    [Temperature.EU.Value]                 FLOAT (53)         NOT NULL,
    [Temperature.Raw.ZeroValue]            INT                NOT NULL,
    [Temperature.Raw.SpanValue]            INT                NOT NULL,
    [Temperature.EU.ZeroValue]             FLOAT (53)         NOT NULL,
    [Temperature.EU.SpanValue]             FLOAT (53)         NOT NULL,
    [RowVersion]                           ROWVERSION         NULL,
    CONSTRAINT [PK_DifferentialPressureMeterProcessVariableValues] PRIMARY KEY CLUSTERED ([MeterId] ASC, [DateTimeStamp] ASC),
    CONSTRAINT [FK_DifferentialPressureMeterProcessVariableValues_Meters] FOREIGN KEY ([MeterId]) REFERENCES [FlowSQL].[Meters] ([Id])
);

